### ISSUE TITLE
Augment shell command functionality

### ISSUE THREAD

**Issue by Gastove** [Gastove/doctopus#22]
At present, the "command" used by a tentacle is stored as a vector of pieces, with the "command" separate, like so:

``` clojure
{:html-command "lein"
 :html-args ["marg" "-f" "index.html"]}
```

There's a couple problems with this:
1. It's a little baffling for a human to write, and easy to get wrong.
2. We cannot support html projects with more than one build step. 
### Proposal

Re-tool to using a single vector-of-vectors, like so:

``` clojure
:html-command [["lein marg -f index.html"]]
```

A command with more-than-one step could go:

``` clojure
:html-command [["npm -i"]
                           ["node bin/mop.js"]]
```

In the backend, we need to implement command splitting and chaining -- that is, each command-vector needs to be converted to a vector of words.

**Comment by jarofghosts** [comment]
We also need a way to denote special words that can be filled into the commands, environment vars maybe?

**Comment by Gastove** [comment]
AH, right. Right right right. For instance:

``` clojure
: html-command [["make-some-html --basepath :url-root
```

**Comment by jarofghosts** [comment]
i feel like we need something that isn't going to collide with possibly valid command syntax, which is why using environment vars and their syntax seemed to make sense. there may be a better solution, though

**Comment by Gastove** [comment]
Yeah. I agree about collisions -- which is part of why I suggested keywords (like `:url-root`). That said, I think usability is the most important part, since the server can accommodate whatever, and the syntax of env-vars is pretty well understood. 

I think, as long as we can provide some guidance in the create/edit web view about how to write a correct command, we should be OK. 

Will do a pass on the server parts of this later today.
