### ISSUE TITLE
Bring in a Database for, at the very least, configuration

### ISSUE THREAD

**Issue by Gastove** [Gastove/doctopus#23]
Right now, we're reading configs from hand-written EDN files, and writing them the same way. That's... neat and all, but it'd make a good deal more sense to use a database for this stuff. For instance: it'd be a heckofa lot easier to create new tentacles in the browser and store them if we were storing them to a database. 
### Proposal: Postgres

It works nicely. There are current, compliant JDBC drivers. There's a low-level Clojure SQL wrapper ([here](https://github.com/clojure/java.jdbc)) and a high-level, abstract wrapper ([Korma](http://sqlkorma.com/)). 

When this is done, there should be a single, "demo" EDN file for Doctopus itself; on bootstrap, Doctopus should make sure it has loaded itself in to postgres, and nothing else.

**Comment by jarofghosts** [comment]
Seems reasonable, I also wondered about sqlite

**Comment by Gastove** [comment]
SQLite doesn't seem like a bad choice at all. I think of PG as being... I dunno, more "enterprise grade" -- by which I mostly mean, we could _eventually_  write a storage backend for HTML against SQL and stop leaning so hard on the local filesystem. 

But: a good question is, do we _want_ to stop using the local filesystem? It does work p. alright.

**Comment by jarofghosts** [comment]
I'm not sure that it's a bad idea to just keep using the filesystem for storing files. I know we briefly discussed having archives and such, but iirc we decided that should be handled by externally.

**Comment by Gastove** [comment]
You know, unless we can find a good reason to stop using the file system,
let's just... Not stop using it. For a while. It is, for instance, working
right now :-D

**Comment by Gastove** [comment]
Alright, so here's a thing I've just realized: I think we need this for #26 (route reloading) _and_ #27 (rebuilding through the UI) to work. Here's why:

So there's this `Doctopus` record that forms a kind of stack: `Doctopus -> Head(s) -> Tentacle(s)`. Thing is: it's all stateful. A `Head` loads its tentacles, then _returns a new head containing those tentacles_. Likewise, a `Doctopus` loads it's heads, then returns a new `Doctopus`. This was a perfectly great way to get things done without a DB, during hackweek. Now it's.... not.... so ideal. 

One way or the other, I think this notion of returning new records containing new state is going to be very difficult to work with going forward. For instance: if we add or modify a `Tentacle`, we'll have to create a new `Doctopus` to serve it :-1:. Instead, we should be able to pull state from some kind of storage, ideally a DB. This could potentially be coupled with, for instance, using `atom`s to contain the present state of, say, a `Head` -- but I think this would put us in the position of a `Tentacle` needing to "notify" a `Head` of its creation, which seems dubious to me.

Thoughts?

**Comment by jarofghosts** [comment]
I agree. And I think simply using the database for statefulness makes the most sense. If we run into performance issues (seems unlikely at least in the short-to-medium term) we can introduce a caching layer or otherwise reevaluate.

**Comment by Gastove** [comment]
:100:

**Comment by jarofghosts** [comment]
Beginnings of a PR here #43

**Comment by Gastove** [comment]
I say this is done, as of #43 and #45
