### ISSUE TITLE
Testing Pass

### ISSUE THREAD

**Issue by Gastove** [Gastove/doctopus#29]
Oh shit do we ever need more/better test coverage. 
#### Here's a partial list of things to test:
- [x] Tentacle
  - [x] Creation
  - [x] Interrogation (what's your route, etc)
- [x] Head
  - [x] Can we get your tentacles?
  - [x] What's your name?
- [x] Doctopus itself (since this is our core abstraction)
- [x] Routing/requests (can be tested with ring.mock)
- [x] Storage
  - [x] Swapping backends
  - [x] Permanent and Temporary backends (turns out these tests never got updated after we changed how a backend loads. Dangit, Ross)
- [x] Templating

**Comment by Gastove** [comment]
On the `testing-pass` branch for anybody who wants to chip in

**Comment by Gastove** [comment]
This is just to say: as always happens, the more tests I try and write, the more cruft I find in (pretty much entirely my) code that needs scrubbing up. WHEE.

**Comment by gmcquillan** [comment]
This is good. We'll whittle it down to a tight codebase.

**Comment by Gastove** [comment]
Ugh. That missing tick box keeps biting me in the face. _Gotta_ get routes under test.
